added compile and simualtion log error in makefile

diff --git a/uart_tx/src/Makefile b/uart_tx/src/Makefile
--- a/uart_tx/src/Makefile
+++ b/uart_tx/src/Makefile
@@ -3,6 +3,9 @@ SHELL := /bin/csh
 
 .ONESHELL:
 
+.SILENT:
+	make main
+
 all: 
 	make main 
 	
@@ -10,7 +13,9 @@ main:
 	source $(QUESTA)
 	make clean
 	vlog -sv +acc +cover +fcover -l uart_tx_top.log uart_tx_top.sv
-	vsim -vopt work.top -voptargs=+acc=npr -assertdebug -l simulation.log -coverage -c -do "coverage save -onexit -assert -directive -cvg -codeAll coverage.ucdb; run -all; exit"
+	make compile_log_err
+	vsim -vopt work.top -voptargs=+acc=npr -assertdebug -l simulation.log -sva -coverage -c -do "log -r /*; add wave -r /*; coverage save -onexit -assert -directive -cvg -codeAll coverage.ucdb; run -all; exit" -wlf waveform.wlf
+	make simulate_log_err
 	vcover report -html coverage.ucdb -htmldir covReport -details
 
 read:
@@ -31,7 +36,37 @@ simulate:
 
 clean:
 	rm -rf transcript work covReport 
-	rm simulation.log wave.vcd uart_tx_top.log coverage.ucdb
+	rm simulation.log wave.vcd uart_tx_top.log coverage.ucdb waveform.wlf
 	clear
 	clear
 
+compile_log_err:
+	echo ""
+	echo "-----------------------------------------------------------------"
+	echo "------------------- Compilation Report --------------------------"
+	echo ""
+	grep "^Errors" uart_tx_top.log
+	echo ""
+	echo "Log file path: uart_tx_top.log"
+	echo ""
+	echo "-----------------------------------------------------------------"
+	echo "-----------------------------------------------------------------"
+	echo ""
+
+simulate_log_err:
+	echo ""
+	echo "------------------------------------------------------------"
+	echo "-------------------- Simulation Report ---------------------"
+	echo ""
+	echo "UVM Fatal"
+	grep "FATAL" simulation.log || echo "No UVM_FATAL"
+	echo ""
+	echo "UVM Errors"
+	grep "ERROR" simulation.log || echo "No UVM_ERROR"
+	echo ""
+	echo "UVM Warnings"
+	grep "WARN" simulation.log || echo "No UVM_WARNING"
+	echo ""
+	echo "Waveform: vsim -view waveform.wlf &"
+	echo "------------------------------------------------------------"
+	echo ""
